### ISSUE TITLE
a paper with DOI, title ect, is not showing

### ISSUE THREAD

**Issue by igormintz** [danielnsilva/semanticscholar#22] opened 2020-10-25 19:38 UTC
thanks a lot for the package!
for example, the paper with the DOI 10.2147/OAJSM.S133406
has all the details. but when i try to retrieve the title or authors name, i get othing
paper=sch.paper('10.2147/OAJSM.S133406')
thanks, Igor

**Comment by danielnsilva** [comment] 2020-10-27 13:33
HI @igormintz. I can't reproduce the error.
```
>>> import semanticscholar as sch
>>> paper = sch.paper('10.2147/OAJSM.S133406')
>>> print(paper['title'])
Patellofemoral pain in athletes
>>> for author in paper['authors']:
...     print(author['name'])
...
W. Petersen
I. Rembitzki
C. Liebau
```

**Comment by igormintz** [comment] 2020-10-29 07:35
you are right, but some how, when I'm iterating over hundreds of citations, the information I get is partial. when I try again later, one-by-one, it works well. is there a limitation over the number of times I can approach semanticscholar? any idea on how to manage it?

**Comment by danielnsilva** [comment] 2020-10-30 06:51
I've never experienced an issue like that. However, I usually do not need to iterate over a huge number of papers. I should point out that Semantic Scholar API calls are limited to 100 requests per 5-minute window, but should not result in a partial response. Actually, you will get a response with HTTP status 429 and the library will handle it.

Right now I have no definitive answer, but I can try to reproduce the issue and help to address it.

- How many requests you are trying to make? 
- Can you identify any pattern relative to the number of requests sent until the issue occurs?
- Which version are you using for semanticscholar package?
- Besides, could you share your code?

**Comment by danielnsilva** [comment] 2020-11-14 22:18
I will close this issue. Feel free to re-open it if you need more help on this issue.

**Closed** 2020-11-14 22:20 UTC
